version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: ./build/rest_server/Dockerfile
    ports:
    - "8000:8000"
    command: rest_server -env /api/.env.dev
    environment:
      DATABASE_HOST: postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:14.0-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}